name: Go Build and Run

on:
  push:
    paths:
      - 'pagemaker/**'
    # branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'pagemaker/go.mod'
      - run: go version
        working-directory: pagemaker

      - name: Build Go
        run: go build
        working-directory: pagemaker

      - name: Update files
        run: ./pagemaker
        working-directory: pagemaker

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update"
